local function sendColor(colorName,name,realm)
	if (nil ~= name and nil ~= realm) then
		SendChatMessage(name..", you are "..colorName.."!", "WHISPER", nil, name.."-"..realm)
	elseif(nil ~= name) then
		SendChatMessage(name..", you are "..colorName.."!", "WHISPER", nil, name)
	end
end


local RedButton = CreateFrame("Button", "MyButton", UIParent, "UIPanelButtonTemplate")
RedButton:SetWidth(100)
RedButton:SetHeight(25)
RedButton:SetPoint("TOP",-200,0)
RedButton:SetText("Red")
RedButton:RegisterForClicks("AnyUp")
RedButton:SetScript("OnClick", function()
	local name, realm = UnitName("target")
	sendColor("RED",name,realm)
end )

local PurpleButton = CreateFrame("Button", "MyButton", UIParent, "UIPanelButtonTemplate")
PurpleButton:SetWidth(100)
PurpleButton:SetHeight(25)
PurpleButton:SetPoint("TOP",-100,0)
PurpleButton:SetText("Purple")
PurpleButton:RegisterForClicks("AnyUp")
PurpleButton:SetScript("OnClick", function()
	local name, realm = UnitName("target")
	sendColor("PURPLE",name,realm)
end )

local GreenButton = CreateFrame("Button", "MyButton", UIParent, "UIPanelButtonTemplate")
GreenButton:SetWidth(100)
GreenButton:SetHeight(25)
GreenButton:SetPoint("TOP")
GreenButton:SetText("Green")
GreenButton:RegisterForClicks("AnyUp")
GreenButton:SetScript("OnClick", function()
	local name, realm = UnitName("target")
	sendColor("GREEN",name,realm)
end )

local YellowButton = CreateFrame("Button", "MyButton", UIParent, "UIPanelButtonTemplate")
YellowButton:SetWidth(100)
YellowButton:SetHeight(25)
YellowButton:SetPoint("TOP",100,0)
YellowButton:SetText("Yellow")
YellowButton:RegisterForClicks("AnyUp")
YellowButton:SetScript("OnClick", function()
	local name, realm = UnitName("target")
	sendColor("YELLOW",name,realm)
end )

local BlueButton = CreateFrame("Button", "MyButton", UIParent, "UIPanelButtonTemplate")
BlueButton:SetWidth(100)
BlueButton:SetHeight(25)
BlueButton:SetPoint("TOP",200,0)
BlueButton:SetText("Blue")
BlueButton:RegisterForClicks("AnyUp")
BlueButton:SetScript("OnClick", function()
	local name, realm = UnitName("target")
	sendColor("BLUE",name,realm)
end )
